//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sys_infomationcategory
    {
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
    }
}
